name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Italic.ttf
          style: italic
        - asset: fonts/Lato-ThinItalic.ttf
          style: italic
        - asset: fonts/Lato-LightItalic.ttf
          style: italic
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic
        - asset: fonts/Lato-BoldItalic.ttf
          style: italic
        - asset: fonts/Lato-Thin.ttf
        - asset: fonts/Lato-Light.ttf
        - asset: fonts/Lato-Regular.ttf
        - asset: fonts/Lato-Bold.ttf
        - asset: fonts/Lato-Black.ttf